export const ACTIONS = {
    DELETETODO: "DELETETODO",
    TOOGLESTATUS: "TOOGLESTATUS",
    UPDATETODO: "UPDATETODO",
    ADDTODO: "ADDTODO",
    GETTODO: "GETTODO",
};

export const GETTERS = {
    NUMBEROFTODOS: "NUMBEROFTODOS",
    COMPLETEDTASKS: "COMPLETEDTASKS",
    LOADING: "LOADING",
    INCOMPLETEDTASKS: "INCOMPLETEDTASKS",
    INCOMPLETEDTASKCOLOR: "INCOMPLETEDTASKCOLOR",
    COMPLETEDTASKCOLOR: "COMPLETEDTASKCOLOR",
    ALLTODOS: "ALLTODOS",
    INCOMPLETETASK: "INCOMPLETETASK",
};

export const MUTATIONS = {
    RESETDEFAULT: "RESETDEFAULT",
};
